### ISSUE TITLE
Database dump please

### ISSUE THREAD

**Issue by yanko-ivanov** [dez-php/phalcon-auth#1]
Hi,
I think it'd be nice if you include the .sql dump for the session and auth tables. 
Currently, if I want to use this, I have to read through the code to understand the database schema.

Greets, and thanks for the great library. :)

**Comment by dez-php** [comment]
@stormweaver thank you for your feedback!
I push new commit with SQL scheme for this library.

I am glad what you liked my solution. 
If you have any questions or ideas, tell me, I will try implement them.

Regards, Ivan
