### ISSUE TITLE
Creating user when logged in as an other one

### ISSUE THREAD

**Issue by kris-terziev** [dez-php/phalcon-auth#2]
Hello,

It would be nice if we could use create to actually create new user even when logged in as an other one. At the moment if you are logged in as a user and do create($email, $password) the current user will be edited.

Also thanks for sharing your awesome work!

**Comment by dez-php** [comment]
@kris-terziev  thank you for your feedback!
In last commit I add SQL file with one test user
With login and password:
`admin@site.local` `admin`

I am very glad what you liked my solution.
If you have any questions or ideas, tell me, I will try implement them.

Regards, Ivan
